/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 home.gltf 
Author: suchart studio (https://sketchfab.com/suchart3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/721db084cfb445c68efde7a36301320f
Title: เฮือนอีสาน
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/home.gltf')
  return (
    <group {...props} dispose={null} scale={0.3}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Plane.007_Baked']}  />
    </group>
  )
}

useGLTF.preload('/home.gltf')
